### ISSUE TITLE
Create README for this application

### ISSUE THREAD

**Issue by amitech** [svcastaneda/code2040-application#1]
Hi,

It is not an issue, I am suggesting to maintain proper documentation so that others can use it and contribute to it.

**All the Best**

Thank you.

**Comment by svcastaneda** [comment]
Hi. This is my CODE2040 fellowship application. I don't think people should be using this code or be contributing to it. 🙂

**Comment by amitech** [comment]
Your code is on public github repository. So if someone is interested, you should give a chance for contribution :)

**Comment by svcastaneda** [comment]
@amitsharma928: I had to make it public because it was for the technical challenge for **_my_** application for a **_fellowship_** with [CODE2040](http://www.code2040.org/).

**Comment by amitech** [comment]
@svcastaneda Ohh. So did you get _fellowship_ with CODE2040 ?
